### ISSUE TITLE
Increase major version when breaking changes are introduced

### ISSUE THREAD

**Issue by halbekanne** [SDA-SE/sda-dropwizard-commons#1727]
The latest release notes [2.54.0](https://github.com/SDA-SE/sda-dropwizard-commons/releases/tag/2.54.0) mention the introduction of breaking changes without updating the major version number.

This goes against [SemVer](https://semver.org) and thus causes unexpected consequences for manual updates as well as automatic updates e.g. when updating the dropwizard-commons lib using Renovate (the change is treated as a minor update, meaning no breaking changes).

If the Dropwizard libs you're distributing through your commons package contain any breaking changes, it should therefore also update the major version number.

**Comment by christopher-cudennec** [comment]
Hi @halbekanne !

Thanks for reaching out to us. The changes in release 2.54.0 were indeed a bit sad. We're currently discussing a similar case and will discuss it internally and with our customers. Would be glad to hear your opinion on the update of [java-jwt](https://github.com/SDA-SE/sda-dropwizard-commons/pull/1681).

So far we were able to stick to version 2 when doing maintenance updates of our libraries. We need to decide if we want to embrace semantic versioning and create breaking change releases more often or if we want to wait for several breaking changes and release them together in one release. It has been a nice coincidence that sda-dropwizard-commons and [Dropwizard](https://github.com/dropwizard/dropwizard) use the same major versions. 😄

**Comment by christopher-cudennec** [comment]
I think we generally agree using semantic versioning. Closing the issue for now.
