### ISSUE TITLE
Proxy-Usage in sda-commons-server-mongo-testing

### ISSUE THREAD

**Issue by lbarnkow** [SDA-SE/sda-dropwizard-commons#2336]
As per documentation, embedded mongo currently picks up proxy settings from env var `http_proxy` but it doesn't seem to use/respect env var `no_proxy`. In our setup accesses to external web server must be made through a web proxy while web servers on our internal network must not use the the web proxy.

Please update the documentation to state that `no_proxy` has no effect or (preferably) make use of the proxy server only when appropriate.

We ran into this problem while setting up local download server for mongo-binaries and setting env var `EMBEDDED_MONGO_DOWNLOAD_PATH`. After unsetting `http_proxy`/`https_proxy` the local download server was used, but other tests that need to use the web proxy fail.

**Comment by christopher-cudennec** [comment]
Hi @lbarnkow!
We'll look into this issue in our next sprint and give you feedback!
Cheers,
Christopher

**Comment by lbarnkow** [comment]
You are correct, we're setting `http_proxy` and `no_proxy` in our Linux environments. I haven't looked at the implementation, but from my point of view it looked like `http_proxy` was picked up (as mentioned in your documentation), but `no_proxy` was not. Our corporate proxy does not handle internal web servers, but I was trying to download embedded mongodb binaries from an internal server.

While simply removing the proxy settings (`http_proxy` env var) would fix the embedded mongodb download, it would break other integration tests that access our OpenId Connect Provider, which is only accessible via the web proxy.

That being said, this is no longer an issue for our setup, so I'm no longer dependent on this issue's resolution. There is an additional local squid proxy server in all our affected Linux environments that handles the `no_proxy` aspect anyways and allows any client to always go through the local proxy. Thus, please proceed with this issue any way you see fit.

**Comment by christopher-cudennec** [comment]
I added this point to the list of possible changes for the next major version: https://github.com/SDA-SE/sda-dropwizard-commons/discussions/2435

**Comment by christopher-cudennec** [comment]
Closing: we've removed the proxy configuration in sda-dropwizard-commons v6.
