### ISSUE TITLE
sda-commons-dependencies - Upgrade to Dropwizard 2.x needed

### ISSUE THREAD

**Issue by mattias88** [SDA-SE/sda-dropwizard-commons#259]
... for Dropwizard JSON Logging

We are using Splunk as log-server and fluentd as log-shipper. A shortcoming of fluentd is the maximum size of a single log statement - 16 KB. Stacktraces easily break this limit. Therefore I want to configure the stacktrace- / exception-handling in Dropwizard-JSON-Logging. This feature 
was added with PR #2501 to Dropwizard 2.x but is missing in Dropwizard 1.x.
Please consider upgrading to Dropwizard 2.x

**Comment by Fox32** [comment]
Hey Mathias, thanks for your suggestion. That is by far not the only reason to update to Dropwizard 2.

- Security updates, but right now 1.3.x is still maintained
- Dependency trouble around Kafka and other libraries
- Compatibility to other Dropwizard libraries

We already started to work on a migration in the branch https://github.com/SDA-SE/sda-dropwizard-commons/tree/feat/dropwizard2.
However we run into some trouble around Jersey and there are some breaking changes were we need a plan how we migrate to the new version.

Right now our roadmap for this not completely clear, but we will work out how we will solve this soon and post an update here.

**Comment by dhenneke** [comment]
We started to actively work on the 2.0 Update in #303 and succeeded to find all issues that need a fix. We are also planning to do some deprecations and removals during the update, and also need to test this internally before we can release the update.

**Comment by JoergSiebahn** [comment]
Some information about the progress on Dropwizard 2:

We created an [alpha release](https://github.com/SDA-SE/sda-dropwizard-commons/releases/tag/2.0.0-alpha-2), that is available at [Maven Central](https://search.maven.org/search?q=g:org.sdase.commons%20v:2.0.0-alhpa-2). The release notes of [1.0.0](https://github.com/SDA-SE/sda-dropwizard-commons/releases/tag/1.0.0) document the deprecations that are removed with the next major version. There is also a [blog post](https://sda.dev/blog/2020/07/22/dropwizard-2-upgrade-guide/) (SDA SE or SDA customer account required) with information about the changes and tasks to do when upgrading.

@mattias88 it would be very helpful, if you can try the alpha release in your service and check for compatibility. We appreciate your feedback.

**Comment by mattias88** [comment]
> @mattias88 it would be very helpful, if you can try the alpha release in your service and check for compatibility. We appreciate your feedback.

I tried the alpha in one of my smaller services. Update was without problems (besides some Deprecations). I was able to configure the exception part in the logging section of my configuration
```
<...>
  appenders:
    - type: console
      layout:
        type: json
        exception:
          rootFirst: true
          depth: full
          evaluators: [org.eclipse.jetty, java.base, org.glassfish.jersey]
<...>
```
Works well, but i didn't do detailed testing beside Exception-Logging

**Comment by dhenneke** [comment]
Thanks for your feedback.

We just released the new update that contains Dropwizard 2.0.13 as [2.0.0](https://github.com/SDA-SE/sda-dropwizard-commons/releases/tag/2.0.0).
