### ISSUE TITLE
Jetty not excluded for version 2 branch

### ISSUE THREAD

**Issue by halbekanne** [SDA-SE/sda-dropwizard-commons#2827]
We're getting dependency check issues with version 2 of the sda commons. Mostly because of Jetty. I'm guessing that this change from the version 5 should be carried over to version 2:

https://github.com/SDA-SE/sda-dropwizard-commons/compare/5.5.20...5.5.21

**Comment by christopher-cudennec** [comment]
Hi @halbekanne!

> I'm guessing that this change from the version 5 should be carried over to version 2

I guess you're right. The tricky part of this change was that we did not get the version conflicts / CVEs anymore when scanning our library here. It only occurred for projects using the commons library and pulling in the transitive dependencies. We will fix that!

> We're getting dependency check issues with version 2 of the sda commons.

In general I recommend to migrate to version 3+. Please note the comment in the [main documentation](https://github.com/SDA-SE/sda-dropwizard-commons/blob/master/README.md):

> Version 2.x.x only receives critical security updates until October 2023. We will only provide security updates for the libraries that are still compatible with Java 8.

We will work on moving to Dropwizard 4 soon and will drop the 2 branch after that.

**Comment by christopher-cudennec** [comment]
I just noted that my colleagues [have already fixed this issue](https://github.com/SDA-SE/sda-dropwizard-commons/pull/2839) while I was on vacation 😄 

Can you confirm that it work for you? Can we close the issue?

**Comment by halbekanne** [comment]
Hi, thanks for your reply. I'm on vacation right now myself, I can check it on Monday.

We'll be looking into moving all services that rely on version 2 over to the newest version then, I'll inform my colleagues about it.

**Comment by christopher-cudennec** [comment]
I assume this is fixed. Please re-open if this is not the case. 😃
