### ISSUE TITLE
sda-commons-server-auth does not validate the JWT's audience

### ISSUE THREAD

**Issue by TheDome** [SDA-SE/sda-dropwizard-commons#3171]
Hi there, 

I currently revise the security architecture of this module. By inspecting teh configuration options of the module SDA Commons Server Auth, I stumbled over the missing validation of the audience. 
By RFC, a service must validate and identify with the audience in a given JWT and reject it, if it does not identify with it [RFC7519]. 
If no audience is given, the service must also enforce, that every JWT has no audience. 

I know this can also be accomplished by putting this check into the OPA policy. However in my opinion, this should be checked while validating the JWT since it is mandatory by standard. 

Is there any reason why the audience is not validated in the given code?

**Comment by JoergSiebahn** [comment]
Hi Dominic,

as you said, we prefer to do any contextual validation in the phase of authorization in OPA. At SDA SE we usually can't enforce that an IDP adds every service that may be part of answering a request to the `aud` claim for various reasons. One is that we depend on the IDP of our customer, the other is that an IDP would know much more details about the internal service architecture than it should. That causes a lot of dependencies. And dependencies, especially a central component that knows about the whole architecture, is what we want to avoid - from a technical and an organizational point of view.

Usually, the audience refers to a end user client that initiates the request. Knowing the client allows us to verify it in the context of a specific endpoint, e.g. some apps are only allowed to read specific data, others can change data. As our services are deployed at multiple customers environments and the APIs are used by their services as well, we need to be very flexible (also for use cases we did not expect) in terms of authorization. Our approach is to move as much as possible to the policy that can be created and tested for each customer environment separately.

I hope this answers your question.

**Comment by TheDome** [comment]
Hi Jörg, 

thanks for the reasoning behind this decision. Now, I can better understand why this desicion has been taken here.
