### ISSUE TITLE
Detect latest release version

### ISSUE THREAD

**Issue by wurstbrot** [SDA-SE/sda-dropwizard-commons#65]
Hi,

sda-commons-bom/README.md shows that I have to include depencies via _$sdaCommonsVersion_ to receive all (direct/transitive) dependencies.

To include the latest version automatically in an other build.gradle using sda-dropwizard-commons, I would like to have a file _relase.txt_ with the latest version number included.

**Comment by Fox32** [comment]
Hello Timo,
Thanks for your suggestion. Right now we aren’t modifying the repository during release creation which would be necessary to include the version number. However you have multiple options:
* Version Tag in the git repository, you can query for the latest tag
* The releases list on GitHub, which is also available using the GitHub API
* List our (private) maven repository for the latest releases of individual artifacts

**Comment by wurstbrot** [comment]
Hi @Fox32,

thank you. The github release is promissing.

Cheers,
Timo
